[workspace]
resolver = "2"
members = ["crates/*"]
default-members = ["crates/cyan"]

[workspace.dependencies]
indoc = "2.0.5"
pretty_assertions = "1.4.1"

[profile.release]
lto = "thin"
panic = "abort"
debug = false
